@baseUrl = http://127.0.0.1:7001


@userId = b499242d-8b8d-4623-9683-eba72346dced
@sellerId = 390ca5f3-c50b-4fd0-9759-1895bde56ae3
# @sellerId = 0c6de44b-6a33-44f1-88f0-a401b854dd50
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoiNzkiLCJ1c2VySWQiOiJiNDk5MjQyZC04YjhkLTQ2MjMtOTY4My1lYmE3MjM0NmRjZWQiLCJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQHFxLmNvbSIsInBob25lIjoiIiwiY3JlYXRlZERhdGUiOiIyMDIwLTEyLTA4VDAyOjA5OjM2Ljc4M1oiLCJpZGVudGl0eXMiOlt7ImlkIjoiNzIiLCJpZGVudGl0eUlkIjoiMmY5NTYyODItMmJhZC00MjE0LTliYzgtMjMzYzU0NzA0MDYxIiwibmFtZSI6IueuoeeQhuWRmCIsImVuYW1lIjoiYWRtaW4iLCJpbmRleCI6Mn1dfSwic3VjY2VzcyI6dHJ1ZSwiY29kZSI6MTAwMTEsImlhdCI6MTYwODE2OTIyMX0.5poQ99-Lb7KwvT2CDa3x8SnZW0k4MfU95o_ZzIE5c5w


####################################

GET {{baseUrl}}

identityList


####################################

#  创建身份列表
POST {{baseUrl}}/api/admin/identityList
Content-Type: application/json

[{
  "name": "超级管理员",
  "ename": "superAdmin",
  "index": 1,
},{
  "name": "管理员",
  "ename": "admin",
  "index": 2,
},{
  "name": "客服",
  "ename": "customerService",
  "index": 3,
},{
  "name": "艺术家",
  "ename": "seller",
  "index": 5,
},{
  "name": "会员",
  "ename": "member",
  "index": 70,
},{
  "name": "用户",
  "ename": "ordinary",
  "index": 80,
},{
  "name": "第三方用户",
  "ename": "thirdParty",
  "index": 90,
}]


####################################

#  修改身份列表
POST {{baseUrl}}/api/admin/identityList/update
Content-Type: application/json

{
  "id": 1,
  "ename": "superAdmins"
}

####################################


#  获取身份列表
GET {{baseUrl}}/api/admin/identityList?ename=admin

####################################

#  删除身份列表
GET {{baseUrl}}/api/admin/identityList/delete



####################################

#  通过身份查找用户
GET {{baseUrl}}/api/admin/identity/user

####################################


#  获取个人信息
# GET {{baseUrl}}/api/user?type=identitys&userId=99597435-1240-42a8-9935-1e001cba76f2
# GET {{baseUrl}}/api/user?userId=99597435-1240-42a8-9935-1e001cba76f2
# GET {{baseUrl}}/api/user?type=identitys
GET {{baseUrl}}/api/user/self?userId=afe96f23-44b6-4e31-ac20-6c13b5b0744f
Authorization: Bearer {{token}}
# GET {{baseUrl}}/api/user/self

####################################


#  注册 普通用户
POST {{baseUrl}}/api/user/register
Content-Type: application/json

{
  "name": "test",
  "phone": "22",
  "password": "123456"
}


####################################

# 登录
POST {{baseUrl}}/api/user/login
Content-Type: application/json

{
  "name": "admin",
  "password": "123"
}


####################################

# 登录后台
POST {{baseUrl}}/api/admin/user/login
Content-Type: application/json

{
  "name": "管理员",
  "password": "123"
}


####################################

#  修改密码
POST {{baseUrl}}/api/user/change/password
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email": "",
  "phone": "15",
  "passwordOld": "123456",
  "passwordNew": "123"
}


####################################

#  找回密码-发送邮件验证码
POST {{baseUrl}}/api/user/password/retrieve/code/send
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userId": "6db20004-97ef-4a9c-8e3b-a69621ee67f5",
  "email": "zpkweb@icloud.com"
}


####################################

#  找回密码-验证邮件验证码
POST {{baseUrl}}/api/user/password/retrieve/code/verify
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userId": "6db20004-97ef-4a9c-8e3b-a69621ee67f5",
  "code": "747215"
}


####################################


#  删除 用户
POST {{baseUrl}}/api/admin/user/remove
Content-Type: application/json



####################################



#  更新用户信息
POST {{baseUrl}}/api/user/update
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "phone": "1234567",
  "name": "test77"
}


####################################

#  获取地址
GET  {{baseUrl}}/api/user/address
Content-Type: application/json
Authorization: Bearer {{token}}



####################################

#  添加用户地址
POST {{baseUrl}}/api/user/address
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userId": "2d956538-2aa3-4bb2-9852-a742bffe17e2",
  "address": {
    "name": "test22",
    "phone": "222",
    "city": "北京",
    "address": ""
  }

}


####################################

#  更新用户地址
POST {{baseUrl}}/api/user/address/update
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userId": "2d956538-2aa3-4bb2-9852-a742bffe17e2",
  "address": {
    "addressId": "dcb34b75-2c9a-458d-924e-5689967e7cfa",
    "name": "test2",
    "phone": "22",
    "city": "北京",
    "address": ""
  }
}


####################################

#  删除用户地址
POST {{baseUrl}}/api/user/address/remove
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userId": "2d956538-2aa3-4bb2-9852-a742bffe17e2",
  "addressId": "6277c751-5748-4f4b-ac4f-de94ac39c60d"
}


####################################



#  申请 艺术家
POST {{baseUrl}}/api/user/seller/apply
Content-Type: application/json

{
  "firstname": "张",
  "lastname": "1",
  "phone": "19",
  "language": "汉语"
}


####################################

#  搜索 艺术家
GET {{baseUrl}}/api/user/seller/search
Authorization: Bearer {{token}}

# {
#   "firstname": "张",
#   "lastname": "三",
#   "phone": "4",
#   "language": "汉语"

# }



####################################



#  通过申请成为艺术家
POST {{baseUrl}}/api/admin/seller/update
Content-Type: application/json

{
  "sellerId": "b3b8a6a1-f6ee-4966-8128-4fe62926dca0"

}



####################################

# 后台添加用户
POST {{baseUrl}}/api/admin/user/register
Content-Type: application/json

{
  "email": "user",
  "identity": "ordinary",
  "name": "user",
  "password": "user",
  "phone": ""

}

####################################

#  搜索 艺术家
GET {{baseUrl}}/api/admin/user/seller/search
Authorization: Bearer {{token}}

####################################


# 添加我喜欢的艺术家
POST {{baseUrl}}/api/my/seller
Content-Type: application/json

{
  "userId": "{{userId}}",
  "sellerId": "0c6de44b-6a33-44f1-88f0-a401b854dd50"

}

####################################

# 我喜欢的艺术家列表
GET {{baseUrl}}/api/my/seller?userId={{userId}}


####################################

# 我喜欢的艺术家是否存在
GET {{baseUrl}}/api/my/seller/has?userId={{userId}}&sellerId={{sellerId}}


####################################

# 删除我喜欢的艺术家
POST {{baseUrl}}/api/my/seller/del
Content-Type: application/json

{
  "userId": "{{userId}}",
  "sellerId": "{{sellerId}}"
}

####################################

# 删除我喜欢的艺术家
POST {{baseUrl}}/api/my/seller/delAll
Content-Type: application/json

{
  "userId": "{{userId}}"

}

####################################








#  搜索 艺术品
GET {{baseUrl}}/api/commodity
Authorization: Bearer {{token}}

####################################


# 添加我喜欢的艺术品
POST {{baseUrl}}/api/my/commodity
Content-Type: application/json

{
  "userId": "{{userId}}",
  "userName": "",
  "commodityId": "6fd67398-38d6-402d-89cc-8bdbe7f4819b",
  "commodityName": ""
}

####################################

# 我喜欢的艺术品列表
GET {{baseUrl}}/api/my/commodity?userId={{userId}}


####################################

# 我喜欢的艺术品是否存在
GET {{baseUrl}}/api/my/commodity/has?userId={{userId}}&commodityId=


####################################

# 删除我喜欢的艺术品
POST {{baseUrl}}/api/my/commodity/del
Content-Type: application/json

{
  "userId": "{{userId}}",
  "commodityId": "6fd67398-38d6-402d-89cc-8bdbe7f4819b"
}

####################################

# 删除我喜欢的艺术品
POST {{baseUrl}}/api/my/commodity/delAll
Content-Type: application/json

{
  "userId": "{{userId}}"

}

####################################




# 添加我的浏览历史
POST {{baseUrl}}/api/my/browsingHistory
Content-Type: application/json

{
  "userId": "{{userId}}",
  "userName": "",
  "commodityId": "6fd67398-38d6-402d-89cc-8bdbe7f4819b",
  "commodityName": ""
}

####################################

# 我的浏览历史
GET {{baseUrl}}/api/my/browsingHistory?userId={{userId}}


####################################
