@baseUrl = http://127.0.0.1:7001


// test2
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI0IiwidXNlcklkIjoiMmQ5NTY1MzgtMmFhMy00YmIyLTk4NTItYTc0MmJmZmUxN2UyIiwibmFtZSI6InRlc3QyIiwiZW1haWwiOiIiLCJwaG9uZSI6IjIiLCJpZGVudGl0eXMiOlt7ImlkIjoiMSIsImlkZW50aXR5SWQiOiIyMWQwYjY2Ni1mZmMzLTQ5NDMtYWMxZC1jMzJhYWExMTdlNWEiLCJuYW1lIjoi55So5oi3IiwiaW5kZXgiOjgwfV0sImlhdCI6MTYwNjE4OTYxMn0.RSywDDayCEQPNjPvw4cdQzdip9HBSX8e3ouygOslNwQ


####################################

GET {{baseUrl}}

identityList


####################################

#  创建身份列表
POST {{baseUrl}}/api/admin/identity
Content-Type: application/json

[{
  "name": "超级管理员",
  "index": 1
},{
  "name": "管理员",
  "index": 2
},{
  "name": "客服",
  "index": 3
},{
  "name": "商家",
  "index": 5
},{
  "name": "会员",
  "index": 70
},{
  "name": "用户",
  "index": 80
},{
  "name": "第三方用户",
  "index": 90
}]


####################################

#  获取身份列表
GET {{baseUrl}}/api/admin/identity

####################################

#  删除身份列表
POST {{baseUrl}}/api/adminidentity/remove




####################################



#  注册 普通用户
POST {{baseUrl}}/api/user/register?locale=en-US
Content-Type: application/json

{
  "name": "test",
  "phone": "1",
  "password": "1"
}


####################################

#  查找 用户
# GET {{baseUrl}}/api/user?type=identitys&userId=99597435-1240-42a8-9935-1e001cba76f2
# GET {{baseUrl}}/api/user?userId=99597435-1240-42a8-9935-1e001cba76f2
# GET {{baseUrl}}/api/user?type=identitys
# GET {{baseUrl}}/api/user?locale=en-US
GET {{baseUrl}}/api/user/self?locale=zh-CN
Authorization: Bearer {{token}}

####################################

#  删除 用户
POST {{baseUrl}}/api/admin/user/remove
Content-Type: application/json



####################################

#  修改密码
POST {{baseUrl}}/api/user/change/password
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "phone": "1234567",
  "password": "123"
}


####################################

#  更新用户信息
POST {{baseUrl}}/api/user/update
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "phone": "1234567",
  "name": "test77"
}


####################################

#  获取地址
GET  {{baseUrl}}/api/user/address
Content-Type: application/json
Authorization: Bearer {{token}}



####################################

#  添加用户地址
POST {{baseUrl}}/api/user/address
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userId": "2d956538-2aa3-4bb2-9852-a742bffe17e2",
  "address": {
    "name": "test22",
    "phone": "222",
    "city": "北京",
    "address": ""
  }

}


####################################

#  更新用户地址
POST {{baseUrl}}/api/user/address/update
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userId": "2d956538-2aa3-4bb2-9852-a742bffe17e2",
  "address": {
    "addressId": "dcb34b75-2c9a-458d-924e-5689967e7cfa",
    "name": "test2",
    "phone": "22",
    "city": "北京",
    "address": ""
  }
}


####################################

#  删除用户地址
POST {{baseUrl}}/api/user/address/remove
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userId": "2d956538-2aa3-4bb2-9852-a742bffe17e2",
  "addressId": "6277c751-5748-4f4b-ac4f-de94ac39c60d"
}


####################################



#  注册 艺术家
POST {{baseUrl}}/api/user/seller/register
Content-Type: application/json

{
  "firstname": "张",
  "lastname": "三",
  "phone": "7",
  "language": "汉语"

}


####################################

#  搜索 艺术家
GET {{baseUrl}}/api/user/seller/search
Authorization: Bearer {{token}}

{
  "firstname": "张",
  "lastname": "三",
  "phone": "4",
  "language": "汉语"

}



####################################

#  通过申请成为艺术家
POST {{baseUrl}}/api/admin/seller/update
Content-Type: application/json

{
  "sellerId": "b3b8a6a1-f6ee-4966-8128-4fe62926dca0"

}



####################################



# 登录
POST {{baseUrl}}/api/user/login
Content-Type: application/json

{
  "phone": "1234567",
  "password": "123456"
}


####################################
