@baseUrl = http://127.0.0.1:7001

//test8
# @token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIzIiwidXNlcklkIjoiNTAwMzhkMmQtODc3Mi00NzY4LThjZTgtODNiMTVkZTY4ZDRjIiwibmFtZSI6InRlc3Q4IiwiZW1haWwiOiIiLCJwaG9uZSI6IjEyMzQ1Njc4IiwiaWRlbnRpdHlzIjpbeyJpZCI6IjgiLCJpZGVudGl0eUlkIjoiMDQxMzc4N2EtOWViMy00OTM1LWE1ZmEtMzc1MmEyNDMzODZlIiwibmFtZSI6IueUqOaItyIsImluZGV4Ijo4MH1dLCJpYXQiOjE2MDYxMjQ1MDZ9.rjSo2aqbkxVJwDREJA1GGjS-Nh8MWSp7rIyHTPA1mx8
// test7
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIyIiwidXNlcklkIjoiNmEwODA0MTUtMjhlMi00YjM5LTk4YTItYzViOTNkYWQ1ZjAwIiwibmFtZSI6InRlc3Q3IiwiZW1haWwiOiIiLCJwaG9uZSI6IjEyMzQ1NjciLCJpZGVudGl0eXMiOlt7ImlkIjoiNyIsImlkZW50aXR5SWQiOiIyYzllMTE3MC1iZmUxLTQ5ZTctYjgyNS1jNGQ2ZTFiOTQwMWMiLCJuYW1lIjoi55So5oi3IiwiaW5kZXgiOjgwfV0sImlhdCI6MTYwNjEyNDc0Nn0.A5kItbi3dOOzphEKAwS3PlTMHLeDN9koD5bTQPed7Nw
// test6
# @token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIxIiwidXNlcklkIjoiY2EyOTE5MTAtYTJiOS00OTMzLWJjOTMtYzg3NWQ0MTU5ZjQzIiwibmFtZSI6InRlc3Q2IiwiZW1haWwiOiIiLCJwaG9uZSI6IjEyMzQ1NiIsImlhdCI6MTYwNjExNzk2NX0.pnJEOv3blPaxEu-jhhEL_3b0SCKKAqFHTvjDk2yET_0


####################################

GET {{baseUrl}}

identityList


####################################

#  创建身份列表
POST {{baseUrl}}/api/admin/identity
Content-Type: application/json

[{
  "name": "超级管理员",
  "index": 1
},{
  "name": "管理员",
  "index": 2
},{
  "name": "客服",
  "index": 3
},{
  "name": "商家",
  "index": 5
},{
  "name": "会员",
  "index": 70
},{
  "name": "用户",
  "index": 80
},{
  "name": "第三方用户",
  "index": 90
}]


####################################

#  获取身份列表
GET {{baseUrl}}/api/admin/identity

####################################

#  删除身份列表
POST {{baseUrl}}/api/adminidentity/remove




####################################



#  注册 普通用户
POST {{baseUrl}}/api/user/register?locale=en-US
Content-Type: application/json

{
  "name": "test8",
  "phone": "12345678",
  "password": "123456"
}


####################################

#  查找 用户
# GET {{baseUrl}}/api/user?type=identitys&userId=99597435-1240-42a8-9935-1e001cba76f2
# GET {{baseUrl}}/api/user?userId=99597435-1240-42a8-9935-1e001cba76f2
# GET {{baseUrl}}/api/user?type=identitys
# GET {{baseUrl}}/api/user?locale=en-US
GET {{baseUrl}}/api/user?locale=zh-CN
Authorization: Bearer {{token}}

####################################

#  删除 用户
POST {{baseUrl}}/api/admin/user/remove
Content-Type: application/json



####################################

#  修改密码
POST {{baseUrl}}/api/user/change/password
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "phone": "1234567",
  "password": "123"
}


####################################

#  注册 艺术家
POST {{baseUrl}}/api/user/register/seller
Content-Type: application/json

{
  "name": "seller",
  "phone": "18612875765",
  "password": "123456"
}


####################################

# 登录
POST {{baseUrl}}/api/user/login
Content-Type: application/json

{
  "phone": "1234567",
  "password": "123456"
}


####################################
